apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-apache-configmap
  namespace: {{ .Values.namespace }}
data:
  index.sh: |-
    #!/bin/bash

     
    hostName=$(hostname)
    #ip=$(hostname -I | head -n 1)
    ip=$(hostname -I | awk '{print $1}') 

    #/var/www/html/index.html
    #cat > index.html << EOF
    echo $hostName > /var/www/html/index.html 
    echo $ip >> /var/www/html/index.html
    apache2-foreground


