apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-apache-configmap
  namespace: {{ .Values.namespace }}
data:
  index.html: | 
    <html>
    <head>
      <title>Task 3 oct frontend</title>
    </head>
    <body>
      <h1> Hostname - {{.Values.podName}} </h1>
      <h1> IP - {{ .Values.podIP }}</h1>
    </body>
    </html>