apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: {{ .Values.image.repository }}
          ports:
            - containerPort: 80
          command: ["/bin/bash"]
          args: ["/tmp/scripts/index.sh"]
          volumeMounts:
            - name: index-html
#              mountPath: /var/www/html/index.html
              mountPath: /tmp/scripts/
#              subPath: index.html              
      volumes:
        - name: index-html
          configMap:
            name: {{ .Release.Name }}-apache-configmap
            items:
              - key: index.sh
                path: index.sh
