apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: web-server
  template:
    metadata:
      labels:
        app: web-server
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP